"""Made email field nullable

Revision ID: 3ae8f7c6d635
Revises: b4bf626e0514
Create Date: 2024-03-15 14:37:56.640775

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ae8f7c6d635'
down_revision = 'b4bf626e0514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mental_health_facility')
    op.drop_table('shelter')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('username')

    op.drop_table('user')
    op.drop_table('food_bank')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_bank',
    sa.Column('foodbank_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('capacity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('contact_phone', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('foodbank_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=True)
        batch_op.create_index('email', ['email'], unique=True)

    op.create_table('shelter',
    sa.Column('shelter_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('capacity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('contact_phone', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('shelter_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('mental_health_facility',
    sa.Column('facility_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('specialization', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('contact_phone', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('facility_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
