"""Initial migration

Revision ID: b4bf626e0514
Revises: 
Create Date: 2024-03-05 15:47:53.261832

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b4bf626e0514'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_banks')
    op.drop_table('mental_health_facilities')
    with op.batch_alter_table('food_bank', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_phone', sa.String(length=20), nullable=True))

    with op.batch_alter_table('mental_health_facility', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_phone', sa.String(length=20), nullable=True))

    with op.batch_alter_table('shelter', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shelter', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('mental_health_facility', schema=None) as batch_op:
        batch_op.drop_column('contact_phone')

    with op.batch_alter_table('food_bank', schema=None) as batch_op:
        batch_op.drop_column('contact_phone')

    op.create_table('mental_health_facilities',
    sa.Column('facility_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('specialization', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('contact_phone', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('facility_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('food_banks',
    sa.Column('foodbank_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('capacity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('contact_phone', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('foodbank_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
